### PR TITLE
ok

### PR DESCRIPTION
**Pull request by jashhhhhhh**

### CODE REVIEW

**Comment by jashhhhhhh** [comment]
whats wrong here??

**Comment by jashhhhhhh** [comment]
this is incredibly confusing, why doesn't the github check give us error codes instead of just saying it failed???? please help

**Comment by jashhhhhhh** [comment]
@halfaro1 ????

**Comment by halfaro1** [comment]
@jashhhhhhh I'm glad you got it, but I want to offer a few tips so you don't experience headaches like it looks you did here. 

You should be using the Python interpreter on your own computer for 90% of the work, and that interpreter will give you detailed error information as you work through it. By the time you get to GitHub you should be pretty much done. The automated error checking on GitHub is used by me for grading and, as a courtesy, I make it available to you all as well so you can see the same thing I'm seeing. So once you get the code running on your personal computer without errors, and you think you've done everything on the instructions, then it's time to synchronize it with GitHub and see the result of the automated test. If you get an error (like you did the first time you submitted it) it's probably best to step back and comb through your code carefully. I would avoid getting into a pattern where you submit every few minutes like you did here - that just creates frustration I think. 

Anyway, hopefully that explanation helped I am here to help if you need it, but it is unlikely I'll be able to answer immediately when you need help, so another suggestion I have is to start days before the assignment is due so you can ask those questions early on and get my response.

**Pull request closed without merging**
