### PR TITLE
Finished

### PR DESCRIPTION
**Pull request by Lamle104**

### CODE REVIEW

**Comment by halfaro1** [comment]
@Lamle104 good work, however, the runner file should not be modified. Could you please put it back to its original form? Add a comment to the pull request when you've finished it.

**Comment by Lamle104** [comment]
I changed the runner back to its original form. But why is it failing now?

**Comment by halfaro1** [comment]
@Lamle104 now there's a problem in lines 1-7 of `guessTheNumberUpgrade.py` -- the code you have there shouldn't be there as it is part of the runner file. Once you fix that it should work. Let me know.

**Comment by Lamle104** [comment]
Yes!!! There we go. Removed lines 1-7 :)

**Comment by halfaro1** [comment]
@Lamle104 fantastic :)

**Pull request closed without merging**
