### PR TITLE
Week 3 'Guess The Number' Assignment

### PR DESCRIPTION
**Pull request by elicegreen**

### CODE REVIEW

**Comment by elicegreen** [comment]
Hi Prof. 
I'm trying to pull my assignment this way because when I click on "pull request" on your(valencia-cop1000-201620) trying to pull it straight onto here after syncing it, it doesn't let me do it.
It does let me pull it under my 'master'... so I did that and then clicked to merge.
Sorry for going around it. I just don't know how to get it pulled directly. Not sure why and what I may be doing wrong.

**Comment by elicegreen** [comment]
The program is running well on my computer... I'm really not sure why it's not passing the checks :-/

**Comment by halfaro1** [comment]
@elicegreen fantastic work :+1:

**Comment by elicegreen** [comment]
Thank you!

**Pull request closed without merging**
