### PR TITLE
Master

### PR DESCRIPTION
**Pull request by haleyhager**

### CODE REVIEW

**Comment by halfaro1** [comment]
@haleyhager you've got a start, but there's a few things you have to get a handle on. First, indentation matters in Python, so go back to the book and review how code should be indented and the repercussions of indenting code in a certain way. Also, the comments contain some very specific instructions that have to be followed, so if a comment says to return a number, for example, that's all it's asking you  to do. In the `generateNumber` function, for example, I noticed you ask the user to choose the upper limit and then you start generating it, but in that function that's not what you're asked to do. I know this is challenging and I'm here to help. Feel free to reach out if you want some extra help.

**Comment by haleyhager** [comment]
Yes, I'm still having issues...between trying to figure out the code for the random number generator which seems so easy but I just can't figure it out. Also I see what you mean with the indent issues as python keeps popping up with those, but some are with the original coding (not mine) and it says "unindent does not match outer indent levels" and I don't know what that means.

**Comment by halfaro1** [comment]
@haleyhager would you like to get together on the phone sometime early next week to talk this over? I think we might get a better understanding that way.

**Comment by haleyhager** [comment]
Hi, I would like to but my work hours don't make that easy. I'm at work from 8 to 5 everyday but the weekend.
________________________________

**Comment by halfaro1** [comment]
@haleyhager that is a little tough, but maybe I could do slightly after 5 one of these days. Let's do it this way - what would you like my input on? I'll try to answer your specific questions. If you refer to line numbers on your code it's easier to comment on.

**Comment by haleyhager** [comment]
@halfaro1 okay, the first issue that is popping up when I run it on python is between lines 55-66. If it's not saying that the syntax is wrong with the 'return' function, it's saying that the indention is wrong.

**Comment by halfaro1** [comment]
@haleyhager yes, that makes sense. if lines 52-62 are part of the `evaluateAnswer` function, they should be indented and line up with line 51

**Comment by halfaro1** [comment]
@haleyhager please see me if you have any questions about this project

**Pull request closed without merging**
