### PR TITLE
guess the number

### PR DESCRIPTION
**Pull request by smoussadeq**

### CODE REVIEW

**Comment by smoussadeq** [comment]
Hello Professor, this is my pull request, will you please take a look at it ?

**Comment by halfaro1** [comment]
@smoussadeq it looks like you removed my started code and wrote your own. Please start with the code I gave you in the assignment and modify only the parts the comments tell you to.

**Comment by smoussadeq** [comment]
will you please take a look at this ?
Thank you so much!!!

**Comment by halfaro1** [comment]
@smoussadeq I see the same issue I described before. Will you please start with the code I provided and only add to the parts mentioned in the comments?

**Comment by smoussadeq** [comment]
can you plz tell me what's the problem..I really don't know what parts to delete or add. Thank you

**Comment by halfaro1** [comment]
@smoussadeq ok, I see that you got my starter code back, that's good. Now, be very carefully when programming. Spelling, capitalization, and indentation matter. Review your code after you check that out.

**Comment by smoussadeq** [comment]
will you plz assist what part i need to fix on this code. Thank you so much!

**Comment by halfaro1** [comment]
@smoussadeq I'm still concerned about the indentation. Take a look through the book to see if it can help you understand how indentation works in Python. If that still doesn't make sense, let's schedule a time to talk on the phone.

**Comment by smoussadeq** [comment]
Finally! Thank you for assistance!

**Comment by smoussadeq** [comment]
Hello Professor ! 
will you please update my grade for week 2 and week 3 ?

**Comment by halfaro1** [comment]
@smoussadeq great work!

**Pull request closed without merging**
