### PR TITLE
Master

### PR DESCRIPTION
**Pull request by BranLWill**

### CODE REVIEW

**Comment by BranLWill** [comment]
Please help me understand why it is not working because it is really bothering me?

**Comment by halfaro1** [comment]
@BranLWill you were making a lot of progress around [here](https://github.com/BranLWill/week3-guess-the-number/commit/c1c057f9b13806d38329d41a12d04e9d9a6820af) but then you started looking at other students' submissions which steered you incorrectly. I'd recommend going back to the pull request you last did on your own and work from there. I'm more than happy to help you.

**Comment by BranLWill** [comment]
how do i get ride of this pull request

**Comment by BranLWill** [comment]
never mind i found it

**Pull request closed without merging**
