### PR TITLE
Update guessTheNumberUpgrade.py

### PR DESCRIPTION
**Pull request by kristinabeck**
Week 3

### CODE REVIEW

**Comment by kristinabeck** [comment]
:+1:  Done!

**Comment by halfaro1** [comment]
@kristinabeck you've got a start, but you have to make sure you follow the instructions to a tee. For example, in the `generateNumber` function, it says that the function should return the random number. That key word, `return`, means something in particular in Python. Chapter 3 will show you about it.

**Comment by kristinabeck** [comment]
Will I be getting any points or credit for this? I still have 0/10

**Comment by halfaro1** [comment]
@kristinabeck if you'd like me to grade it as is, let me know. I was giving you an opportuniy to correct it for a full score.

**Comment by kristinabeck** [comment]
I will try and make the correction


Thank you!


________________________________

**Comment by halfaro1** [comment]
@kristinabeck 
Thanks for continuing to work on this project! Unfortunately, I have to grade this project as-is. I am closing out this pull request and entering your grade on Blackboard. Please see your grade there.

**Pull request closed without merging**
