### PR TITLE
Week 3 changes

### PR DESCRIPTION
**Pull request by Chummel**

### CODE REVIEW

**Comment by Chummel** [comment]
Mr. Halfaro,
I'd like to discuss this pull request and get it into working condition.

**Comment by halfaro1** [comment]
@Chummel you're off to a good start, but your syntax is a little off. Remember that in Python, indentation matters. So things like your `return` statements should be indented inside your `if` statements. Additionally, the `generateNumber()` function should return the value it calculates. If you want to talk through this further, I'm happy to work with you.

**Comment by Chummel** [comment]
I think whats slipping me up is the generateNumber() function

**Comment by halfaro1** [comment]
@Chummel you've made a lot of progress! wow! Take a look at line 85 though, you don't need that. The code I gave you already takes care of that in line 112. For this assignment, you only need to add exactly what it says in the TO DO comments.

**Comment by Chummel** [comment]
I'm confused on what I'm missing, it looks good to me.

**Comment by halfaro1** [comment]
@Chummel your code looks alright but the first thing that pops out at me is the inconsistent indentation. Remember that indentation matters in Python. Try making sure that the indentation is consistent. No tabs for the top-level stuff (function definitions, for example). One tab for anything that sits as part of the function. Two tabs for things that are even deeper in, like the body of an if-statement that's also inside a function.

**Comment by Chummel** [comment]
I feel like I did my indentation yet I'm wondering what you think.

**Comment by halfaro1** [comment]
@Chummel  Good job on all your indentations, how about Line 76, 79, 81?

**Comment by Chummel** [comment]
Hey Mr. Alfaro, It's still not showing checked and I was just wondering what else you saw needed fixing? Thanks.

**Comment by halfaro1** [comment]
@Chummel how come your print statements have a colon (:)? That's not part of Python syntax, take a look at how to use print in the textbook. Are you running the code on your computer, as well, before submitting it on here? If not, I'd like to show you how so you get a little feedback from the error messages.

**Comment by Chummel** [comment]
Whenever  I attempt to run the program on my computer it opens and then closes automatically before I get the chance to look at it.

**Comment by halfaro1** [comment]
@Chummel let's schedule some time to chat on the phone to see if we can work through the issues together. When are you free?

**Comment by halfaro1** [comment]
@Chummel 
Thanks for continuing to work on this project! Unfortunately, I have to grade this project as-is. I am closing out this pull request and entering your grade on Blackboard. Please see your grade there.

**Pull request closed without merging**
