### PR TITLE
Brandon s small guessing game

### PR DESCRIPTION
**Pull request by BranLWill**

### CODE REVIEW

**Comment by halfaro1** [comment]
this one is good too, @BranLWill. Close out whichever pull request you're not going to use for submission. If you're going to use this one, I'd recommend double checking your indentations, especially around the if-statements. Once you correct that it should pass.

**Comment by BranLWill** [comment]
I have no idea what the problem is I have double checked and tripled checked my indentations but they look fine in the ":(" commit. When i look at the details of the error it states that this following line "if( showAnswer == True ):" haves an IndentationError: unexpected indent. but then i got ride of the indent and it still showed the same error.

**Comment by halfaro1** [comment]
@BranLWill check your indentations in line 102-108. Remember that indentation matters in Python.

**Comment by BranLWill** [comment]
Yah I checked those indentations and it's still not working

**Comment by BranLWill** [comment]
i checked the indentations and it's still not working any suggestions

**Comment by halfaro1** [comment]
@BranLWill I think the issue here is not with your code at this point, everything looks fine there, but with the fact that you're editing a different file (`Week_3_Guessing_Game.py`). For the automated testing to work, your code has to be in `guessTheNumberUpgrade.py`. If you copy and paste your working code to that file, the automated test should pass.

**Comment by BranLWill** [comment]
Thank you

**Comment by halfaro1** [comment]
@BranLWill that was a quick fix. Great work!

**Pull request closed without merging**
