### PR TITLE
1st change

### PR DESCRIPTION
**Pull request by nhatnam113**

### CODE REVIEW

**Comment by halfaro1** [comment]
@nhatnam113 great progress, you are almost there! I'll give you one more hint, and that's to use the `generateNumber()` function within the `playGame()` function.

**Comment by nhatnam113** [comment]
Thank you professor for your hint, I'm very appreciate about that.
I'll fix right away.
null
________________________________

**Comment by nhatnam113** [comment]
Professor I have a question about W3
About 400%. Is that the maximum score for W3 because I forgot to click finish when I'm done that
Please answer me as soon as you can
Thank you very much
________________________________

**Comment by nhatnam113** [comment]
Hi Professor,
Can you take a look for me? I tried to fix it but It's still failed.

**Comment by halfaro1** [comment]
@nhatnam113 your name on the first line should be a comment.

**Comment by halfaro1** [comment]
@nhatnam113 good work! You'll see this grade update on Blackboard soon.

**Pull request closed without merging**
